language: java

env:
  global:
    - MAVEN_OPTS: "'-Dorg.slf4j.simpleLogger.defaultLogLevel=warn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'"
    - secure: "IJTnGhAcLBAh5gWZfOdWe/CrT5MiwO7nZGChlu3pdQiZ0Fmuu2CXgXKz9nmsDW75QZ3Y5KI6gIGRTrimtU6lIfBG2R5TBbHL6DVh9v1U8gnWgl+HEm/x0eUBp5pR6VSB9mO07ZYjanujNzslTm4VfNRTiJJHaCQcxjZxpgJa+6Vte0wpjx21eMc1cyfjkeUbCbra1LcmictLfeKxCwjOYwui5yuE4sztvcP2tdUd8OEgs0Xnc4+c/Q+SPd3yFzjN22zIKubk1aUXi4mUodJnZGnKsTYTTVnEXIgEEXD/DYwGvL6Lzq+miuLgmaYEIFpkbGAO4f9wbFoQSbyPPLP11EvKDp862PrDxKPDJw/d1W0KoO6+Ewm9pQRHjN0tIST/mTUA6BUJQ/2FKT2LpJo+SQq+HvHQqpJvhL4Uq928ZPdOrpSMH9HpnZooVEeQiZth/qYZLyg1vkUh9/qxuXDt9qAKbo+yqiD+aOsi5B7z9YFK4LunIrpNzBqNB1Tqu2Mm3T4G53mmGT05OMfvfB+BndoeWQ9nV7ewlJPzvAXWYtOWIaQ3S+zALIFg+3WyctSny2MzuXfwl7n0xZkiQs+uCkrZ2Ms/CIIVXJ0yPsb3ANzjqCd0IOayXiR0yEmTz6q/O6OsI3pGOHwM1F8awcdtL8H4hu9k6vJTW6FKtJ4lR/I="
    - secure: "aZPFA04ZitXoX4U9kjs3TRlOwlwN7F/1QAxrRRQq1NXZnq9Lm1DAKMz05weSXdU2yW+OHLFqQyRGSPBgCEWZBTfrFPM0/VlH6XGA0Hf9HLM+gW8hNP4TKzSKfmWae15G8986N0Iwy9dUS2sGJkK1wTl2f8dqTqULjIWXWbhL52qHvgDN5LRN1GmmE8ZJlKDk1w9a5xqS4eNvb85qWMF1NXk5LlBeS01SLSrJ/ZFl8KSdFZvCg/Sw9L2JbNM/YOd7Ba1LFXLxul2B96RYCU2z5eb3Hxuim3F/UyrbpFQ5s00azvPMDnfkheIONrjwQsR8ShiDYQ5g79opaF0iGaYJuVYMs6SG8lN8y5B/szK7tLjhF4fRruRMqHjH0A5ahcXIDcGLhs5+iBK1fl4TijC6JO/NthWEk8PaRJEi4MxB4zDo02ve64Q8aO25rU+glwmp9NfNwn0OrYHrsCb1m6upzE0m1PvTY0eYSW1DZ0SzPRfPo3JzRkEjthL2SSqQG4D5FhjuQXiME6m1cBzjsb5j2++sloVaEJbT8bwOErhK7Ley0Ro8gtMvmI1c6pQ9Dxnh/N8P0MmQ+7X4DMkyH/HqZOuckQ2qk1McRL4fmWyG03OiXmlJwi6m/fXSO4O1uDkW9cchYQviKcvU1KmCkChseR7QJpbRNFZAdpaw/YXNrTc="
    - secure: "B2aR/ybMLoliMnA5Gt3+Vqq7xONq1W/7t6KI3Fpre/i3yQt0w3Eplydm/ygTUdSHWccwU/OQZpgDtnSChjJBk0uhFnX16HXgwVRyDB7WRSjzvgJ3Z2gDNYj4gpXq/UWHISDhJbdFA/SzQGXjkacJsWm5oSLkje9zy2H+G5BzET1JBA6SQJlzs1FuELsdwV6TDa2qFS3p3nJswScE5IN2EI9A3Suo6W+r5EzY30aN+dsb6C7JuXjbdw96L93tQU3dG/sI0xEl1ePkkPfwj5kYjz0WCYrTjUCIcwCouS3WVr5WrOhWiK16QeRCkcXKUhwJa/vLXiDWCzsXlfH8WJRFAJie1zd/vCQFdMQyx0S3qKpcJ9yUFct6eFJBT5JvPlRbGv82+PK/1BIzyeEDuZmZJDtC+8bi7pl7/MEUycbe2odoQZuJh0J3OhDnJ1OiloDZWm5G025/Uo8JacocKMfD7Nbd9IkFbMhElHmm4087zHmfJD0pXDDDzjWMBe7gcTiHCR78o4Bryc87JrXqwd+6dG6G49qqPzp8NzA+YUk4o61idUKgrxfUHf1gELNzbUz9skvwl0yNTVPZTzNw0x7AxvGyy6Rg5H7K+35lYtljKcGZbtXqg1L221JVJvN92jbgqEitSaXk0FGPd/ifklIqcuTY2K5UMkHCNlAQbgixMC4="

jdk:
  - openjdk7
  
before_install:
  - openssl aes-256-cbc -K $encrypted_c2ba7c32533d_key -iv $encrypted_c2ba7c32533d_iv -in secrets.tar.enc -out secrets.tar -d
  - tar xvf secrets.tar
  - bash prepare_environment.sh
  

install: true

script:
  - "mvn clean install > >(egrep -v 'Download(ing|ed) ')"

after_failure:
  # Print the maven log for more information
  - cat */target/work/data/.metadata/.log
