language: java 

env:
  global:
    - MAVEN_OPTS=-Dorg.slf4j.simpleLogger.defaultLogLevel=warning

jdk:
  - openjdk7
  - openjdk8
  - oraclejdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - oraclejdk11

install: true

script:
  - mvn clean install 
