language: java 

env:
  global:
    - MAVEN_OPTS: "'-Dorg.slf4j.simpleLogger.defaultLogLevel=warn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn'"

jdk:
  - openjdk7
  - openjdk8
  - oraclejdk8

install: true

script:
  - "mvn clean install > >(egrep -v 'Download(ing|ed) ')"

after_failure:
  # Print the maven log for more information
  - cat */target/work/data/.metadata/.log
