language: java 

env:
  global:
    - MAVEN_OPTS=\"-Dorg.slf4j.simpleLogger.defaultLogLevel=warn -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn\"

jdk:
  - openjdk7
  - openjdk8
  - oraclejdk8
  - openjdk9
  - openjdk10
  - openjdk11
  - oraclejdk11

install: true

script:
  - mvn clean install 

after_failure
  # Print the maven log for more information
  - cat target/work/data/.metadata/.log
